# Generated by Django 5.1.2 on 2024-10-15 22:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Authors',
            fields=[
                ('id', models.BigAutoField(db_column='id', primary_key=True, serialize=False)),
                ('activate', models.BooleanField(db_column='activate', default=False)),
                ('created_at', models.DateTimeField(db_column='created_at')),
                ('modified_at', models.DateTimeField(db_column='modified_at')),
                ('name', models.CharField(db_column='name', max_length=70)),
            ],
            options={
                'abstract': False,
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Genres',
            fields=[
                ('id', models.BigAutoField(db_column='id', primary_key=True, serialize=False)),
                ('activate', models.BooleanField(db_column='activate', default=False)),
                ('created_at', models.DateTimeField(db_column='created_at')),
                ('modified_at', models.DateTimeField(db_column='modified_at')),
                ('name', models.CharField(db_column='name', max_length=70)),
            ],
            options={
                'abstract': False,
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('id', models.BigAutoField(db_column='id', primary_key=True, serialize=False)),
                ('activate', models.BooleanField(db_column='activate', default=False)),
                ('created_at', models.DateTimeField(db_column='created_at')),
                ('modified_at', models.DateTimeField(db_column='modified_at')),
                ('name', models.CharField(db_column='name', max_length=70)),
                ('age', models.IntegerField(db_column='age')),
                ('cpf', models.CharField(db_column='cpf', max_length=12)),
                ('favourite_genre', models.ForeignKey(db_column='favourite_genre', on_delete=django.db.models.deletion.DO_NOTHING, to='basic_library.genres')),
            ],
            options={
                'abstract': False,
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(db_column='id', primary_key=True, serialize=False)),
                ('activate', models.BooleanField(db_column='activate', default=False)),
                ('created_at', models.DateTimeField(db_column='created_at')),
                ('modified_at', models.DateTimeField(db_column='modified_at')),
                ('title', models.CharField(db_column='title', max_length=70)),
                ('number_pages', models.IntegerField(db_column='number_pages')),
                ('copies', models.IntegerField(db_column='available_copies')),
                ('id_author', models.ForeignKey(db_column='id_author', on_delete=django.db.models.deletion.DO_NOTHING, to='basic_library.authors')),
                ('id_genre', models.ForeignKey(db_column='id_genre', on_delete=django.db.models.deletion.DO_NOTHING, to='basic_library.genres')),
            ],
            options={
                'abstract': False,
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Loans',
            fields=[
                ('id', models.BigAutoField(db_column='id', primary_key=True, serialize=False)),
                ('loan_day', models.DateField(auto_now_add=True, db_column='loan_day')),
                ('return_day', models.DateField(auto_now_add=True, db_column='return_day')),
                ('id_book', models.ForeignKey(db_column='id_book', on_delete=django.db.models.deletion.CASCADE, to='basic_library.books')),
                ('id_client', models.ForeignKey(db_column='id_client', on_delete=django.db.models.deletion.CASCADE, to='basic_library.clients')),
            ],
        ),
    ]
