# Generated by Django 5.1.2 on 2024-10-16 02:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basic_library', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='books',
            old_name='copies',
            new_name='available_copies',
        ),
    ]
