# Generated by Django 5.1.2 on 2024-10-16 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_library', '0002_rename_copies_books_available_copies'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authors',
            name='created_at',
            field=models.DateTimeField(auto_now=True, db_column='created_at'),
        ),
        migrations.AlterField(
            model_name='authors',
            name='modified_at',
            field=models.DateTimeField(auto_now_add=True, db_column='modified_at'),
        ),
        migrations.AlterField(
            model_name='books',
            name='created_at',
            field=models.DateTimeField(auto_now=True, db_column='created_at'),
        ),
        migrations.AlterField(
            model_name='books',
            name='modified_at',
            field=models.DateTimeField(auto_now_add=True, db_column='modified_at'),
        ),
        migrations.AlterField(
            model_name='clients',
            name='created_at',
            field=models.DateTimeField(auto_now=True, db_column='created_at'),
        ),
        migrations.AlterField(
            model_name='clients',
            name='modified_at',
            field=models.DateTimeField(auto_now_add=True, db_column='modified_at'),
        ),
        migrations.AlterField(
            model_name='genres',
            name='created_at',
            field=models.DateTimeField(auto_now=True, db_column='created_at'),
        ),
        migrations.AlterField(
            model_name='genres',
            name='modified_at',
            field=models.DateTimeField(auto_now_add=True, db_column='modified_at'),
        ),
    ]
